### PR TITLE
Fixed MacOS M1 build

### PR DESCRIPTION
**Pull request by ahcorde**
Related with this issue https://github.com/ros-perception/point_cloud_transport/issues/56

FYI @pfavr2

### CODE REVIEW

**Comment by pfavr2** [comment]
Thanks - I only had to change 2 occurrences and you changed 4.

I'll test it in a few hours.

**Review by clalancette — APPROVED** [review]
This looks to be a subset of #55.  This looks good to me with green CI.

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/20310/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/14721/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21047/)

**Comment by pfavr2** [comment]
Yes it builds on MacOS M1 also. Thanks!

**Pull request merged**
